const FETCH_ALL_USERS_REQUEST = 'FETCH_ALL_USERS_REQUEST';
const FETCH_ALL_USERS_SUCCESS = 'FETCH_ALL_USERS_SUCCESS';
const FETCH_ALL_USERS_FAILED = 'FETCH_ALL_USERS_FAILED';

export {
    FETCH_ALL_USERS_REQUEST,
    FETCH_ALL_USERS_SUCCESS,
    FETCH_ALL_USERS_FAILED
}